增加部署流程用时的控制台输出
AnYiEE/AwesomeGadgets pull request #28
Opened 2024-06-09 21:50 UTC by ZoruaFox

2024-06-10 13:01 UTC, AnYiEE requested changes

2024-06-11 06:37 UTC, ZoruaFox commented on scripts/modules/deploy.ts
> +		}
> ```ts
> const timeTaken = minutes > 0
>  ? `${minutes} minutes and ${Math.floor(seconds)} seconds`
>  : `${Math.floor(seconds)} seconds`;
> 
> console.log(chalk.blue(`Deployment took ${timeTaken}.`));
> ```
> 
> 项目里还有Moment.js，或许可以：
> 
> ```ts
> const format = 'YYYY-MM-DD HH:mm:ss';
> 
> const startTime = moment();
> const startTimeFormatted = startTime.format(format);
> 
> const endTime = moment();
> const totalSeconds = endTime.diff(startTime, 'seconds');
> 
> const minutes = Math.floor(totalSeconds / 60);
> const seconds = totalSeconds % 60;
> 
> const endTimeFormatted = endTime.format(format);
> 
> const timeTaken = minutes > 0
>  ? `${minutes} minutes and ${seconds} seconds`
>  : `${seconds} seconds`;
> ```

已作出更改，本地分支测试通过。

2024-06-11 12:21 UTC, rpuboh commented
BTW, I feel that @AnYiEE probably intends to make this project internationalized (open to be used by other mediawiki sites). Therefore the code comments should better be in English (consistent with rest of the codebase).

2024-06-12 07:15 UTC, AnYiEE approved these changes

2024-06-12 07:22 UTC, merged